### ISSUE TITLE
Multiple Failures using Helix

### ISSUE THREAD

**Issue by jellyton255** [Srlion/Hook-Library#1]
Hello there, when using SAM, or this hook library, multiple functions of a gamemode called Helix cease to function. It doesn't entirely break the addon, but multiple key features are broken. I was wondering if there is anything you can do to fix this.

**Example of problems:**
_Failed font creation:_

```
[ERROR] gamemodes/helix/plugins/wepselect.lua:74: 'ixWeaponSelectFont' isn't a valid font
1. SetFont - [C]:-1
2. v - gamemodes/helix/plugins/wepselect.lua:74
3. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:477
```

_Failure to save/alter helix data._
_Failure to load certain plugins in their entirety._

Here is a link to the gamemode's github: https://github.com/nebulouscloud/helix
And their discord: https://discord.gg/2AutUcF
This is the helix schema I'm using: https://github.com/NebulousCloud/helix-hl2rp

**Comment by Srlion** [comment]
I have tested it before and it works fine? Did you test with no addons installed?

**Comment by jellyton255** [comment]
I did not, but I have a spare server that I can test it with.

**Comment by Srlion** [comment]
Really weird, when defining the hook library using "module" function it works fine, I have updated the hook library and it should work fine.

**Comment by jellyton255** [comment]
Weird, I tested it with no addons, and it worked fine. Are there any known addons that conflict?

**Comment by Srlion** [comment]
It won’t conflict with any addon, and I really can’t figure out why it works when using “module”
