### ISSUE TITLE
Let Hooks return more than 6 Values

### ISSUE THREAD

**Issue by Yolo-TM** [Srlion/Hook-Library#3]
![image](https://user-images.githubusercontent.com/66616587/189166041-1ed6d377-bb20-49a4-8be5-e59f35dd13f9.png)

Wouldn't it make sense to allow Hooks return more than 6 Values?

As Seen here Lua Allows to collect all return Values in one Table:
![image](https://user-images.githubusercontent.com/66616587/189166294-96024cd1-802d-4140-9a6d-c75a345dc017.png)
![image](https://user-images.githubusercontent.com/66616587/189166317-33d27b4f-e082-40e4-9125-731bc1f314b5.png)

Idk if it  would consume much Performance, but I think it would be great to let hooks return more values

Greetings

**Comment by Srlion** [comment]
I follow what default hook lib does
Adding what you want would mess the performance ye
